# Generated by Django 5.2.15 on 2026-06-23 06:44

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🌿', max_length=16)),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('display_order', 'name'),
                'indexes': [models.Index(fields=['is_featured', 'display_order'], name='cat_featured_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('seller_name', models.CharField(default='OrganicMart Verified', max_length=140)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('package_size', models.CharField(blank=True, max_length=80)),
                ('origin', models.CharField(blank=True, max_length=120)),
                ('organic_certification', models.CharField(max_length=180)),
                ('benefits', models.TextField(help_text='One benefit per line.')),
                ('ingredients', models.TextField(help_text='One ingredient per line.')),
                ('image_emoji', models.CharField(default='🥬', max_length=16)),
                ('image_gradient', models.CharField(default='linear-gradient(135deg, #eef6df, #ffffff)', max_length=120)),
                ('rating_average', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=16)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ('-is_featured', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer_name', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('is_verified_purchase', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_featured'], name='prod_status_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='prod_category_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='catalog_product_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='catalog_product_stock_gte_0'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'is_approved'], name='review_product_approved_idx'),
        ),
    ]
